# Use official Python slim image
FROM python:3.11-slim

# Set working directory
WORKDIR /app-test

# Copy requirements and install dependencies
COPY requirements.app-test.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.app-test.txt

# Copy application code
COPY ./app-test /app-test

# Expose FastAPI port
EXPOSE 8000

# Command to run the app with Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]

