[package]
name = "catserver"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.3"
axum-macros = "0.5.0"
reqwest = { version = "0.12.15", features = ["stream"] }
tokio = { version = "1.44.2", features = ["rt", "rt-multi-thread"] }
