from environs import Env

env = Env()
env.read_env()

DEBUG = env.bool("DEBUG", default=False)
RUNTIME_ENV = env.str("RUNTIME_ENV", default="local")

POSTGRES_USER = env.str("POSTGRES_USER")
POSTGRES_PASSWORD = env.str("POSTGRES_PASSWORD")
POSTGRES_DB_NAME = env.str("POSTGRES_DB_NAME")

if RUNTIME_ENV == "docker":
    POSTGRES_HOST = env.str("POSTGRES_HOST")
    POSTGRES_PORT = env.str("POSTGRES_PORT")
    VALKEY_HOST = env.str("VALKEY_HOST")
    VALKEY_PORT = env.str("VALKEY_PORT")
else:
    POSTGRES_HOST = env.str("POSTGRES_HOST_LOCAL")
    POSTGRES_PORT = env.str("POSTGRES_PORT_LOCAL")
    VALKEY_HOST = env.str("VALKEY_HOST_LOCAL")
    VALKEY_PORT = env.str("VALKEY_PORT_LOCAL")

POSTGRES_GENERAL_DB_URL = f"postgresql+asyncpg://{POSTGRES_USER}:{POSTGRES_PASSWORD}@{POSTGRES_HOST}:{POSTGRES_PORT}"
POSTGRES_DB_URL = f"{POSTGRES_GENERAL_DB_URL}/{POSTGRES_DB_NAME}"
POSTGRES_DB_RETENTION_DAYS = 14

VALKEY_DB = env.str("VALKEY_DB")
VALKEY_SPOT_EXPIRATION = env.int("VALKEY_SPOT_EXPIRATION", default=60)
VALKEY_GEO_EXPIRATION = env.int("VALKEY_GEO_EXPIRATION", default=3600)

USERNAME_FOR_TELNET_CLUSTERS = env.str("USERNAME_FOR_TELNET_CLUSTERS")

QRZ_USER = env.str("QRZ_USER")
QRZ_PASSOWRD = env.str("QRZ_PASSWORD")
QRZ_API_KEY = env.str("QRZ_API_KEY")
QRZ_SESSION_KEY_REFRESH = env.int("QRZ_SESSION_KEY_REFRESH")
