/* automatically generated by rust-bindgen 0.71.1 */

pub const RIG_MODEL_NONE: u32 = 0;
pub const RIG_VFO_NONE: u32 = 0;
pub const RIG_MODE_NONE: u32 = 0;
pub type rig_model_t = u32;
pub type rot_model_t = u32;
pub type azimuth_t = f64;
pub type elevation_t = f64;
pub type ROT = s_rot;
pub const rig_errcode_e_RIG_OK: rig_errcode_e = 0;
pub const rig_errcode_e_RIG_EINVAL: rig_errcode_e = 1;
pub const rig_errcode_e_RIG_ECONF: rig_errcode_e = 2;
pub const rig_errcode_e_RIG_ENOMEM: rig_errcode_e = 3;
pub const rig_errcode_e_RIG_ENIMPL: rig_errcode_e = 4;
pub const rig_errcode_e_RIG_ETIMEOUT: rig_errcode_e = 5;
pub const rig_errcode_e_RIG_EIO: rig_errcode_e = 6;
pub const rig_errcode_e_RIG_EINTERNAL: rig_errcode_e = 7;
pub const rig_errcode_e_RIG_EPROTO: rig_errcode_e = 8;
pub const rig_errcode_e_RIG_ERJCTED: rig_errcode_e = 9;
pub const rig_errcode_e_RIG_ETRUNC: rig_errcode_e = 10;
pub const rig_errcode_e_RIG_ENAVAIL: rig_errcode_e = 11;
pub const rig_errcode_e_RIG_ENTARGET: rig_errcode_e = 12;
pub const rig_errcode_e_RIG_BUSERROR: rig_errcode_e = 13;
pub const rig_errcode_e_RIG_BUSBUSY: rig_errcode_e = 14;
pub const rig_errcode_e_RIG_EARG: rig_errcode_e = 15;
pub const rig_errcode_e_RIG_EVFO: rig_errcode_e = 16;
pub const rig_errcode_e_RIG_EDOM: rig_errcode_e = 17;
pub const rig_errcode_e_RIG_EDEPRECATED: rig_errcode_e = 18;
pub const rig_errcode_e_RIG_ESECURITY: rig_errcode_e = 19;
pub const rig_errcode_e_RIG_EPOWER: rig_errcode_e = 20;
pub const rig_errcode_e_RIG_ELIMIT: rig_errcode_e = 21;
pub const rig_errcode_e_RIG_EACCESS: rig_errcode_e = 22;
pub const rig_errcode_e_RIG_EEND: rig_errcode_e = 23;
pub type rig_errcode_e = ::std::os::raw::c_uint;
pub type RIG = s_rig;
pub const rig_status_e_RIG_STATUS_ALPHA: rig_status_e = 0;
pub const rig_status_e_RIG_STATUS_UNTESTED: rig_status_e = 1;
pub const rig_status_e_RIG_STATUS_BETA: rig_status_e = 2;
pub const rig_status_e_RIG_STATUS_STABLE: rig_status_e = 3;
pub const rig_status_e_RIG_STATUS_BUGGY: rig_status_e = 4;
pub type rig_status_e = ::std::os::raw::c_uint;
pub type freq_t = f64;
pub type shortfreq_t = ::std::os::raw::c_long;
pub type vfo_t = ::std::os::raw::c_uint;
pub type pbwidth_t = shortfreq_t;
pub type hamlib_token_t = ::std::os::raw::c_long;
pub const rig_conf_e_RIG_CONF_STRING: rig_conf_e = 0;
pub const rig_conf_e_RIG_CONF_COMBO: rig_conf_e = 1;
pub const rig_conf_e_RIG_CONF_NUMERIC: rig_conf_e = 2;
pub const rig_conf_e_RIG_CONF_CHECKBUTTON: rig_conf_e = 3;
pub const rig_conf_e_RIG_CONF_BUTTON: rig_conf_e = 4;
pub const rig_conf_e_RIG_CONF_BINARY: rig_conf_e = 5;
pub const rig_conf_e_RIG_CONF_INT: rig_conf_e = 6;
pub type rig_conf_e = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct confparams {
    pub token: hamlib_token_t,
    pub name: *const ::std::os::raw::c_char,
    pub label: *const ::std::os::raw::c_char,
    pub tooltip: *const ::std::os::raw::c_char,
    pub dflt: *const ::std::os::raw::c_char,
    pub type_: rig_conf_e,
    pub u: confparams__bindgen_ty_1,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union confparams__bindgen_ty_1 {
    pub n: confparams__bindgen_ty_1__bindgen_ty_1,
    pub c: confparams__bindgen_ty_1__bindgen_ty_2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct confparams__bindgen_ty_1__bindgen_ty_1 {
    pub min: f32,
    pub max: f32,
    pub step: f32,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct confparams__bindgen_ty_1__bindgen_ty_2 {
    pub combostr: [*const ::std::os::raw::c_char; 16usize],
}
pub type rmode_t = u64;
#[repr(C)]
#[repr(align(8))]
pub struct rig_caps {
    pub _bindgen_opaque_blob: [u64; 3260usize],
}
#[repr(C)]
#[repr(align(8))]
pub struct s_rig {
    pub _bindgen_opaque_blob: [u64; 5991usize],
}
#[repr(C)]
#[repr(align(8))]
pub struct s_rot {
    pub _bindgen_opaque_blob: [u64; 4096usize],
}
unsafe extern "C" {
    pub fn rig_init(rig_model: rig_model_t) -> *mut RIG;
}
unsafe extern "C" {
    pub fn rot_init(rot_model: rot_model_t) -> *mut ROT;
}
unsafe extern "C" {
    pub fn rot_open(rot: *mut ROT) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rot_close(rot: *mut ROT) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rot_cleanup(rot: *mut ROT) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rot_set_position(
        rot: *mut ROT,
        azimuth: azimuth_t,
        elevation: elevation_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rot_get_position(
        rot: *mut ROT,
        azimuth: *mut azimuth_t,
        elevation: *mut elevation_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rot_confparam_lookup(
        rot: *mut ROT,
        name: *const ::std::os::raw::c_char,
    ) -> *const confparams;
}
unsafe extern "C" {
    pub fn rot_set_conf(
        rot: *mut ROT,
        token: hamlib_token_t,
        val: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rot_token_foreach(
        rot: *mut ROT,
        cfunc: ::std::option::Option<
            unsafe extern "C" fn(
                *const confparams,
                *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rot_list_foreach(
        cfunc: ::std::option::Option<
            unsafe extern "C" fn(
                *const rot_caps,
                *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
#[repr(C)]
pub struct rot_caps {
    pub _bindgen_opaque_blob: [u64; 512usize],
}
unsafe extern "C" {
    pub fn rot_load_all_backends() -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn roterror(errnum: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
#[repr(C)]
pub struct hamlib_sys_rot_caps_metadata {
    pub rot_model: ::std::os::raw::c_int,
    pub model_name: *const ::std::os::raw::c_char,
    pub mfg_name: *const ::std::os::raw::c_char,
    pub version: *const ::std::os::raw::c_char,
    pub status: rig_status_e,
}
unsafe extern "C" {
    pub fn hamlib_sys_rot_caps_metadata(
        caps: *const rot_caps,
    ) -> *const hamlib_sys_rot_caps_metadata;
}
unsafe extern "C" {
    pub fn rig_open(rig: *mut RIG) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_set_freq(rig: *mut RIG, vfo: vfo_t, freq: freq_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_get_freq(rig: *mut RIG, vfo: vfo_t, freq: *mut freq_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_set_mode(
        rig: *mut RIG,
        vfo: vfo_t,
        mode: rmode_t,
        width: pbwidth_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_get_mode(
        rig: *mut RIG,
        vfo: vfo_t,
        mode: *mut rmode_t,
        width: *mut pbwidth_t,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_set_vfo(rig: *mut RIG, vfo: vfo_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_get_vfo(rig: *mut RIG, vfo: *mut vfo_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_set_conf(
        rig: *mut RIG,
        token: hamlib_token_t,
        val: *const ::std::os::raw::c_char,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_get_conf2(
        rig: *mut RIG,
        token: hamlib_token_t,
        val: *mut ::std::os::raw::c_char,
        val_len: ::std::os::raw::c_int,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_ext_func_foreach(
        rig: *mut RIG,
        cfunc: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut RIG,
                arg2: *const confparams,
                arg3: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_ext_level_foreach(
        rig: *mut RIG,
        cfunc: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut RIG,
                arg2: *const confparams,
                arg3: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_ext_parm_foreach(
        rig: *mut RIG,
        cfunc: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *mut RIG,
                arg2: *const confparams,
                arg3: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_ext_lookup(rig: *mut RIG, name: *const ::std::os::raw::c_char) -> *const confparams;
}
unsafe extern "C" {
    pub fn rig_ext_lookup_tok(rig: *mut RIG, token: hamlib_token_t) -> *const confparams;
}
unsafe extern "C" {
    pub fn rig_ext_token_lookup(
        rig: *mut RIG,
        name: *const ::std::os::raw::c_char,
    ) -> hamlib_token_t;
}
unsafe extern "C" {
    pub fn rig_token_foreach(
        rig: *mut RIG,
        cfunc: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *const confparams,
                arg2: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_confparam_lookup(
        rig: *mut RIG,
        name: *const ::std::os::raw::c_char,
    ) -> *const confparams;
}
unsafe extern "C" {
    pub fn rig_token_lookup(rig: *mut RIG, name: *const ::std::os::raw::c_char) -> hamlib_token_t;
}
unsafe extern "C" {
    pub fn rig_close(rig: *mut RIG) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_cleanup(rig: *mut RIG) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_get_caps(rig_model: rig_model_t) -> *mut rig_caps;
}
unsafe extern "C" {
    pub fn rigerror(errnum: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn rigerror2(errnum: ::std::os::raw::c_int) -> *const ::std::os::raw::c_char;
}
unsafe extern "C" {
    pub fn rig_list_foreach(
        cfunc: ::std::option::Option<
            unsafe extern "C" fn(
                arg1: *const rig_caps,
                arg2: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_list_foreach_model(
        cfunc: ::std::option::Option<
            unsafe extern "C" fn(
                rig_model: rig_model_t,
                arg1: *mut ::std::os::raw::c_void,
            ) -> ::std::os::raw::c_int,
        >,
        data: *mut ::std::os::raw::c_void,
    ) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_load_backend(be_name: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_check_backend(rig_model: rig_model_t) -> ::std::os::raw::c_int;
}
unsafe extern "C" {
    pub fn rig_load_all_backends() -> ::std::os::raw::c_int;
}
pub const HAMLIB_SYS_RIG_MODEL_DUMMY: _bindgen_ty_17 = 1;
pub const HAMLIB_SYS_RIG_VFO_A: _bindgen_ty_17 = 1;
pub const HAMLIB_SYS_RIG_VFO_B: _bindgen_ty_17 = 2;
pub const HAMLIB_SYS_RIG_VFO_CURR: _bindgen_ty_17 = 536870912;
pub const HAMLIB_SYS_RIG_MODE_AM: _bindgen_ty_17 = 1;
pub const HAMLIB_SYS_RIG_MODE_CW: _bindgen_ty_17 = 2;
pub const HAMLIB_SYS_RIG_MODE_USB: _bindgen_ty_17 = 4;
pub const HAMLIB_SYS_RIG_MODE_LSB: _bindgen_ty_17 = 8;
pub const HAMLIB_SYS_RIG_MODE_FM: _bindgen_ty_17 = 32;
pub type _bindgen_ty_17 = ::std::os::raw::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct hamlib_sys_rig_caps_metadata {
    pub rig_model: rig_model_t,
    pub model_name: *const ::std::os::raw::c_char,
    pub mfg_name: *const ::std::os::raw::c_char,
    pub version: *const ::std::os::raw::c_char,
    pub copyright: *const ::std::os::raw::c_char,
    pub status: rig_status_e,
}
unsafe extern "C" {
    pub fn hamlib_sys_rig_caps_metadata(
        caps: *const rig_caps,
    ) -> *const hamlib_sys_rig_caps_metadata;
}
unsafe extern "C" {
    pub fn hamlib_sys_configure_debug(
        callback: ::std::option::Option<
            unsafe extern "C" fn(
                level: ::std::os::raw::c_int,
                message: *const ::std::os::raw::c_char,
            ),
        >,
    );
}
