import { TOUR_CLOSE_LEFT_PANEL_EVENT } from "./tour_events.js";

export const TOUR_COMPLETED_CHAPTERS_KEY = "tour_completed_chapters";
export const DEFAULT_TOUR_CHAPTER_ID = "quick_start";

const action_buttons = ["back", "close"];
const scroll_target_to_center = selector => () => {
    if (window.innerWidth <= 768) {
        document.dispatchEvent(new Event(TOUR_CLOSE_LEFT_PANEL_EVENT));
    }

    return new Promise(resolve => {
        requestAnimationFrame(() => {
            document
                .querySelector(selector)
                ?.scrollIntoView({ block: "center", inline: "nearest" });
            resolve();
        });
    });
};

export const TOUR_CHAPTERS = {
    quick_start: {
        id: "quick_start",
        title: "Quick Start",
        description: "A short introduction to the main Holy Cluster workflow.",
        steps: [
            {
                target: "[data-tour='top-bar']",
                title: "Welcome",
                content:
                    "Welcome to The Holy Cluster. This short tour shows where the main controls live.",
                placement: "center",
                skipBeacon: true,
            },
            {
                target: "[data-tour='top-bar-time-limit']",
                title: "Spot Window",
                content: "Use this selector to choose how far back the live spot list should look.",
                placement: "bottom",
            },
            {
                target: "[data-tour='top-bar-submit-spot']",
                title: "Submit Spots",
                content: "This button opens the spot submission form when you want to add a spot.",
                placement: "bottom",
            },
            {
                target: "[data-tour='top-bar-settings']",
                title: "Settings",
                content:
                    "Open settings here to configure your station, display, filters, and imports.",
                placement: "bottom",
            },
            {
                target: "[data-tour='top-bar-left-menu']",
                title: "Open The Filter Rail",
                content: "Click this menu button if the band and mode filter rail is hidden.",
                optional: true,
                waitFor: "[data-tour='left-column']",
                buttons: action_buttons,
                placement: "bottom",
            },
            {
                target: "[data-tour='left-column']",
                title: "Band And Mode Filters",
                content: "The left rail filters spots by band and mode with one-click toggles.",
                optional: true,
                placement: "right",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='mobile-main-tabs']",
                title: "Map And Table Tabs",
                content: "On narrow screens, use these tabs to switch between the map and table.",
                mobileOnly: true,
                optional: true,
                placement: "center",
                mobileHideOverlay: true,
            },
            {
                target: "[data-tour='map-panel']",
                title: "Map",
                content:
                    "The map shows where spots are coming from and gives quick geographic context.",
                desktopOnly: true,
                optional: true,
                placement: "right",
                spotlightPadding: 0,
            },
            {
                target: "[data-tour='table-panel']",
                title: "Spots Table",
                content: "The table gives a detailed sortable view of the current spots.",
                desktopOnly: true,
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='top-bar-right-menu']",
                title: "Open The Side Panel",
                content: "Click this menu button if the side panel is hidden.",
                optional: true,
                waitFor: "[data-tour='side-panel']",
                buttons: action_buttons,
                placement: "bottom",
            },
            {
                target: "[data-tour='side-panel-tabs']",
                title: "Feature Panels",
                content:
                    "These tabs switch between advanced filters, band activity, heatmap, DXpeditions, and ADIF tools.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='tour-launcher']",
                title: "Tour Launcher",
                content: "Use this launcher to restart this tour or choose a more focused chapter.",
                placement: "top",
            },
        ],
    },
    map: {
        id: "map",
        title: "Map",
        description: "Learn the map controls, overlays, and propagation indicators.",
        steps: [
            {
                target: "[data-tour='mobile-main-tabs']",
                title: "Show The Map",
                content: "Tap the Map tab if the map is not currently visible.",
                mobileOnly: true,
                optional: true,
                waitFor: "[data-tour='map-controls']",
                buttons: action_buttons,
                placement: "center",
                mobileHideOverlay: true,
                showWhenAlreadySatisfied: true,
                skipBeacon: true,
            },
            {
                target: "[data-tour='map-panel']",
                title: "Map View",
                content:
                    "The map shows active spots geographically and helps you spot regional openings.",
                desktopOnly: true,
                optional: true,
                placement: "right",
                skipBeacon: true,
                spotlightPadding: 0,
            },
            {
                target: "[data-tour='map-controls']",
                title: "Map Controls",
                content:
                    "These buttons reset the map, open display controls, and switch map features.",
                placement: "left",
            },
            {
                target: "[data-tour='map-gps']",
                title: "GPS Location",
                content: "Use this button to center the map on your current GPS location.",
                mobileOnly: true,
                placement: "left",
            },
            {
                target: "[data-tour='map-reset']",
                title: "Reset Map",
                content: "Use this to return the map to your configured home view.",
                placement: "left",
            },
            {
                target: "[data-tour='map-fullscreen']",
                title: "Fullscreen Map",
                content: "This expands the map for a larger operating view.",
                desktopOnly: true,
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='map-controls-toggle']",
                title: "Open Map Controls",
                content: "Click this controls button to open the map display panel.",
                waitFor: "[data-tour='map-controls-panel']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='map-controls-panel']",
                title: "Display Panel",
                content:
                    "This panel contains map projection, overlays, and geographic display options.",
                placement: "left",
            },
            {
                target: "[data-tour='map-projection-toggle']",
                title: "Try Projection",
                content: "Click this button to switch between globe and azimuthal projections.",
                buttons: action_buttons,
                placement: "left",
                waitForChange: {
                    selector: "[data-tour='map-projection-toggle']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='map-night-toggle']",
                title: "Try Night Overlay",
                content: "Click this button to toggle the day/night terminator overlay.",
                buttons: action_buttons,
                placement: "left",
                waitForChange: {
                    selector: "[data-tour='map-night-toggle']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='map-equator-toggle']",
                title: "Try Equator",
                content: "Click this button to toggle the equator overlay.",
                buttons: action_buttons,
                placement: "left",
                waitForChange: {
                    selector: "[data-tour='map-equator-toggle']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='map-overlay-dxcc']",
                title: "Try A Zone Overlay",
                content:
                    "Click DXCC to toggle entity labels. These overlay buttons are exclusive, so enabling one disables the others.",
                buttons: action_buttons,
                placement: "left",
                waitForChange: {
                    selector: "[data-tour='map-overlay-dxcc']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='map-region-overlay-us_state']",
                title: "Try A Regional Overlay",
                content: "Click US state to toggle the state overlay.",
                buttons: action_buttons,
                placement: "left",
                waitForChange: {
                    selector: "[data-tour='map-region-overlay-us_state']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='propagation-bars']",
                title: "Propagation",
                content: "These indicators summarize current A, K, and solar flux conditions.",
                optional: true,
                requires: "propagation_loaded",
                placement: "top",
            },
        ],
    },
    spots_table: {
        id: "spots_table",
        title: "Spots Table",
        description: "Learn the live spots table, search, sorting, and spot row fields.",
        steps: [
            {
                target: "[data-tour='mobile-main-tabs']",
                title: "Show The Table",
                content: "Tap the Table tab if the spots table is not currently visible.",
                mobileOnly: true,
                optional: true,
                waitFor: "[data-tour='spots-table']",
                buttons: action_buttons,
                placement: "center",
                mobileHideOverlay: true,
                skipBeacon: true,
            },
            {
                target: "[data-tour='table-panel']",
                title: "Table View",
                content: "The table is the detailed sortable view of live spots.",
                desktopOnly: true,
                optional: true,
                placement: "left",
                skipBeacon: true,
            },
            {
                target: "[data-tour='table-search']",
                title: "Callsign Search",
                content:
                    "Search for a callsign here, then press Enter to create a show-only filter.",
                desktopOnly: true,
                optional: true,
                placement: "bottom",
            },
            {
                target: "[data-tour='table-search-mobile']",
                title: "Callsign Search",
                content:
                    "Search for a callsign here, then press Enter to create a show-only filter.",
                mobileOnly: true,
                optional: true,
                placement: "top",
            },
            {
                target: "[data-tour='table-search-single-spot-toggle']",
                title: "Single Spot Mode",
                content:
                    "Click this toggle to switch between all spots and only the newest spot per station.",
                desktopOnly: true,
                optional: true,
                buttons: action_buttons,
                placement: "bottom",
                waitForChange: {
                    selector: "[data-tour='table-search-single-spot-toggle']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='table-search-mobile-single-spot-toggle']",
                title: "Single Spot Mode",
                content:
                    "Tap this toggle to switch between all spots and only the newest spot per station.",
                mobileOnly: true,
                optional: true,
                buttons: action_buttons,
                placement: "top",
                waitForChange: {
                    selector: "[data-tour='table-search-mobile-single-spot-toggle']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='table-header-dx_callsign']",
                title: "Columns And Sorting",
                content: "Click the DX column header to change the table order.",
                buttons: action_buttons,
                placement: "bottom",
                mobilePlacement: "auto",
                waitForChange: {
                    selector: "[data-tour='table-header-dx_callsign']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='spot-row']",
                title: "Spot Row",
                content: "Click this row to pin the spot on the map.",
                optional: true,
                requires: "has_spots",
                buttons: action_buttons,
                before: scroll_target_to_center("[data-tour='spot-row']"),
                placement: "top",
                mobilePlacement: "auto",
                mobileHideOverlay: true,
                mobileScrollOffset: 96,
                skipScroll: true,
                waitForChange: {
                    selector: "[data-tour='spot-row']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='spot-row-dx-callsign']",
                title: "Right-Click A Callsign",
                content:
                    "Right-click this DX callsign to open callsign actions. Spotter callsigns use the same menu.",
                optional: true,
                requires: "has_spots",
                buttons: action_buttons,
                before: scroll_target_to_center("[data-tour='spot-row-dx-callsign']"),
                placement: "top",
                mobilePlacement: "auto",
                mobileHideOverlay: true,
                mobileScrollOffset: 96,
                skipScroll: true,
                waitFor: "[data-tour='table-context-menu'][data-tour-state='callsign']",
            },
            {
                target: "[data-tour='table-context-menu']",
                title: "Callsign Actions",
                content:
                    "This menu can open QRZ, pin the spot, or create callsign filters. Click outside it or press Esc to close it.",
                requires: "has_spots",
                buttons: action_buttons,
                placement: "top",
                mobilePlacement: "auto",
                waitForGone: "[data-tour='table-context-menu']",
            },
            {
                target: "[data-tour='spot-row-flag']",
                title: "Right-Click A Flag",
                content: "Right-click this flag or entity cell to open entity filter actions.",
                optional: true,
                requires: "has_spots",
                buttons: action_buttons,
                before: scroll_target_to_center("[data-tour='spot-row-flag']"),
                placement: "top",
                mobilePlacement: "auto",
                mobileHideOverlay: true,
                mobileScrollOffset: 96,
                skipScroll: true,
                waitFor: "[data-tour='table-context-menu'][data-tour-state='flag']",
            },
            {
                target: "[data-tour='table-context-menu']",
                title: "Entity Actions",
                content:
                    "This menu creates alert, show-only, or hide filters for the entity. Click outside it or press Esc to close it.",
                requires: "has_spots",
                buttons: action_buttons,
                placement: "top",
                mobilePlacement: "auto",
                waitForGone: "[data-tour='table-context-menu']",
            },
            {
                target: "[data-tour='spot-row-frequency']",
                title: "Frequency",
                content: "Click the frequency to send mode and frequency to the connected radio.",
                optional: true,
                requires: "has_spots",
                before: scroll_target_to_center("[data-tour='spot-row-frequency']"),
                placement: "top",
                mobilePlacement: "auto",
                mobileScrollOffset: 96,
                skipScroll: true,
            },
            {
                target: "[data-tour='spot-row-band']",
                title: "Band",
                content: "The band column helps you scan activity by band at a glance.",
                optional: true,
                requires: "has_spots",
                before: scroll_target_to_center("[data-tour='spot-row-band']"),
                placement: "top",
                mobilePlacement: "auto",
                mobileScrollOffset: 96,
                skipScroll: true,
            },
            {
                target: "[data-tour='spot-row-mode']",
                title: "Mode",
                content: "The mode column shows how the spot was classified.",
                optional: true,
                requires: "has_spots",
                before: scroll_target_to_center("[data-tour='spot-row-mode']"),
                placement: "top",
                mobilePlacement: "auto",
                mobileScrollOffset: 96,
                skipScroll: true,
            },
            {
                target: "[data-tour='spot-row-comment']",
                title: "Comment",
                content: "On wide screens, comments provide extra spot details and references.",
                desktopOnly: true,
                optional: true,
                requires: "has_spots",
                before: scroll_target_to_center("[data-tour='spot-row-comment']"),
                placement: "top",
                skipScroll: true,
            },
        ],
    },
    filters: {
        id: "filters",
        title: "Filters",
        description: "Learn the band, mode, and advanced filter controls.",
        steps: [
            {
                target: "[data-tour='top-bar-left-menu']",
                title: "Open The Filter Rail",
                content: "Click this menu button if the band and mode filter rail is hidden.",
                optional: true,
                waitFor: "[data-tour='left-column']",
                buttons: action_buttons,
                placement: "bottom",
                skipBeacon: true,
            },
            {
                target: "[data-tour='left-column']",
                title: "Quick Filters",
                content:
                    "The left rail contains fast band and mode filters for the live spot stream.",
                placement: "right",
                mobilePlacement: "center",
                skipBeacon: true,
            },
            {
                target: "[data-tour='band-filter-20']",
                title: "Band Filters",
                content: "Click the 20m band button to toggle that band in the live spot stream.",
                requires: "manual_band_filter_available",
                buttons: action_buttons,
                placement: "right",
                mobilePlacement: "auto",
                waitForChange: {
                    selector: "[data-tour='band-filter-20']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='filter-options-trigger-bands-20']",
                title: "Open Band Options",
                content: "Hover over the 20m band button to open its ONLY and ALL shortcuts.",
                requires: "manual_band_filter_available",
                buttons: action_buttons,
                placement: "right",
                mobilePlacement: "auto",
                mobileHideOverlay: true,
                waitFor: "[data-tour='filter-options-popup'][data-tour-state='bands-20']",
            },
            {
                target: "[data-tour='filter-options-popup']",
                title: "ONLY And ALL",
                content:
                    "ONLY keeps just this band enabled. ALL turns the available band buttons back on.",
                requires: "manual_band_filter_available",
                forceFilterOptions: {
                    filter_key: "bands",
                    filter_value: 20,
                },
                placement: "right",
                mobilePlacement: "auto",
            },
            {
                target: "[data-tour='mode-filter-SSB']",
                title: "Mode Filters",
                content: "Click SSB to toggle that mode in the table and map.",
                buttons: action_buttons,
                placement: "right",
                mobilePlacement: "auto",
                waitForChange: {
                    selector: "[data-tour='mode-filter-SSB']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='radio-band-filter-group']",
                title: "Radio Band Filter",
                content: "When a radio is available, this can follow the current radio band.",
                optional: true,
                requires: "radio_available",
                placement: "right",
            },
            {
                target: "[data-tour='top-bar-right-menu']",
                title: "Open The Side Panel",
                content: "Click this menu button if the advanced filter panel is hidden.",
                optional: true,
                waitFor: "[data-tour='side-panel']",
                buttons: action_buttons,
                placement: "bottom",
            },
            {
                target: "[data-tour='side-panel-tab-filters']",
                title: "Filters Tab",
                content:
                    "Click the Filters tab to show advanced alert, show-only, and hide filters.",
                buttons: action_buttons,
                placement: "left",
                mobilePlacement: "auto",
                waitForChange: {
                    selector: "[data-tour='side-panel-tab-filters']",
                    attribute: "data-tour-state",
                    satisfiedValue: "active",
                },
            },
            {
                target: "[data-tour='filters-panel']",
                title: "Advanced Filters",
                content:
                    "Advanced filters can alert, show only matching spots, or hide matching spots.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='filter-section-alert']",
                title: "Alert Filters",
                content: "Alert filters keep matching spots visible and visually highlighted.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='filter-section-show_only']",
                title: "Show-Only Filters",
                content: "Show-only filters limit the interface to matching spots.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='filter-section-hide']",
                title: "Hide Filters",
                content: "Hide filters remove matching spots from the table and map.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='add-filter-button-alert']",
                title: "Create A Filter",
                content: "Click Add to open the filter editor for a new alert filter.",
                waitFor: "[data-tour='filter-modal-content']",
                buttons: action_buttons,
                placement: "left",
                mobilePlacement: "auto",
            },
            {
                target: "[data-tour='filter-modal-content']",
                title: "Filter Editor",
                content:
                    "The editor combines an action, a match type, and the required values for that type.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='filter-modal-action-alert']",
                title: "Filter Action",
                content:
                    "The action decides what happens when a spot matches: highlight it, show only matching spots, or hide matching spots. Keep Alert selected for this exercise.",
                placement: "left",
                mobilePlacement: "auto",
            },
            {
                target: "[data-tour='filter-modal-type-prefix']",
                title: "Filter Type",
                content:
                    "The type decides what the filter matches. You can match callsigns, entities, zones, comments, ADIF status, self spots, or DXpeditions.",
                placement: "left",
                mobilePlacement: "auto",
            },
            {
                target: "[data-tour='filter-modal-spot-role-dx']",
                title: "DX Or Spotter",
                content:
                    "Use this to decide whether the callsign-style filter applies to the spotted DX station or the reporting spotter.",
                placement: "left",
                mobilePlacement: "auto",
            },
            {
                target: "[data-tour='filter-modal-text-value']",
                title: "Type A Value",
                content: "Focus this input and type a callsign prefix or any valid filter value.",
                placement: "left",
                mobilePlacement: "auto",
                mobileHideOverlay: true,
            },
            {
                target: "[data-tour='modal-apply-button']",
                title: "Add A Filter",
                content:
                    "Enter any valid value, leave the action as Alert, then click Apply to create the filter.",
                buttons: action_buttons,
                placement: "top",
                mobilePlacement: "auto",
                mobileHideOverlay: true,
                waitForChange: {
                    selector: "[data-tour='filter-section-alert']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='filter-line-alert']",
                title: "Drag The New Filter",
                content:
                    "Drag the new alert filter into the Show-Only section to change what it does.",
                buttons: action_buttons,
                placement: "left",
                mobilePlacement: "auto",
                mobileHideOverlay: true,
                waitForChange: {
                    selector: "[data-tour='filter-section-show_only']",
                    attribute: "data-tour-state",
                },
            },
            {
                target: "[data-tour='filter-section-show_only']",
                title: "Filter Moved",
                content:
                    "The same filter now lives in Show-Only. Dragging between sections changes the filter action without rebuilding it.",
                placement: "left",
                mobilePlacement: "center",
            },
        ],
    },
    side_panel: {
        id: "side_panel",
        title: "Side Panel",
        description: "Tour the side panel tools and tabs.",
        steps: [
            {
                target: "[data-tour='top-bar-right-menu']",
                title: "Open The Side Panel",
                content: "Click this menu button if the side panel is hidden.",
                optional: true,
                waitFor: "[data-tour='side-panel']",
                buttons: action_buttons,
                placement: "bottom",
                skipBeacon: true,
            },
            {
                target: "[data-tour='side-panel']",
                title: "Side Panel",
                content:
                    "The side panel groups deeper tools that do not fit in the main map/table view.",
                placement: "left",
                mobilePlacement: "center",
                skipBeacon: true,
            },
            {
                target: "[data-tour='side-panel-tabs']",
                title: "Panel Tabs",
                content: "Use these tabs to switch between the side panel tools.",
                placement: "left",
                mobilePlacement: "auto",
            },
            {
                target: "[data-tour='side-panel-tab-filters']",
                title: "Filters View",
                content: "Click the Filters tab to show the advanced filter builder.",
                buttons: action_buttons,
                placement: "left",
                mobilePlacement: "auto",
                waitForChange: {
                    selector: "[data-tour='side-panel-tab-filters']",
                    attribute: "data-tour-state",
                    satisfiedValue: "active",
                },
            },
            {
                target: "[data-tour='side-panel-view-filters']",
                title: "Filters View",
                content: "This view contains advanced alert, show-only, and hide filter sections.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='side-panel-tab-band-bar']",
                title: "Band Bar View",
                content: "Click the Band Bar tab to inspect activity by band.",
                buttons: action_buttons,
                placement: "left",
                mobilePlacement: "auto",
                waitForChange: {
                    selector: "[data-tour='side-panel-tab-band-bar']",
                    attribute: "data-tour-state",
                    satisfiedValue: "active",
                },
            },
            {
                target: "[data-tour='band-bar-panel']",
                title: "Band Activity",
                content:
                    "The band bar summarizes activity and spot distribution for a selected band.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='band-bar-selector']",
                title: "Band Selector",
                content: "Choose which band the activity chart should show.",
                optional: true,
                placement: "left",
                mobilePlacement: "auto",
            },
            {
                target: "[data-tour='band-bar-chart']",
                title: "Activity Chart",
                content: "The chart helps you quickly compare activity within the selected band.",
                optional: true,
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='band-bar-legend']",
                title: "Legend",
                content: "The legend explains the chart colors and categories.",
                optional: true,
                placement: "left",
                mobilePlacement: "auto",
            },
            {
                target: "[data-tour='side-panel-tab-heatmap']",
                title: "Heatmap View",
                content: "Click the Heatmap tab to inspect activity density by region.",
                buttons: action_buttons,
                placement: "left",
                mobilePlacement: "auto",
                waitForChange: {
                    selector: "[data-tour='side-panel-tab-heatmap']",
                    attribute: "data-tour-state",
                    satisfiedValue: "active",
                },
            },
            {
                target: "[data-tour='heatmap-panel']",
                title: "Heatmap",
                content: "The heatmap highlights where current activity is concentrated.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='heatmap-continent-selector']",
                title: "Heatmap Region",
                content: "Change the selected continent to focus the heatmap.",
                placement: "left",
                mobilePlacement: "auto",
            },
            {
                target: "[data-tour='side-panel-tab-dxpeditions']",
                title: "DXpeditions View",
                content: "Click the DXpeditions tab to show tracked expedition activity.",
                buttons: action_buttons,
                placement: "left",
                mobilePlacement: "auto",
                waitForChange: {
                    selector: "[data-tour='side-panel-tab-dxpeditions']",
                    attribute: "data-tour-state",
                    satisfiedValue: "active",
                },
            },
            {
                target: "[data-tour='dxpeditions-panel']",
                title: "DXpeditions",
                content: "This panel tracks active DXpeditions and their related spots.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='dxpeditions-summary']",
                title: "DXpedition Summary",
                content: "The summary shows the current expedition activity at a glance.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='dxpeditions-filter']",
                title: "DXpedition Filters",
                content: "Use these controls to narrow which DXpeditions are shown.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='dxpeditions-sort']",
                title: "DXpedition Sorting",
                content: "Sort DXpeditions by the view that is most useful while operating.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='side-panel-tab-missing']",
                title: "Missing View",
                content: "Click the ADIF tab to show ADIF worked tracking.",
                buttons: action_buttons,
                placement: "left",
                mobilePlacement: "auto",
                waitForChange: {
                    selector: "[data-tour='side-panel-tab-missing']",
                    attribute: "data-tour-state",
                    satisfiedValue: "active",
                },
            },
            {
                target: "[data-tour='hunter-panel']",
                title: "Missing And Worked",
                content:
                    "This panel uses your ADIF data to track what you have worked and still need.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='hunter-adif-import']",
                title: "ADIF Import",
                content: "Import ADIF logs here so the ADIF panel can track your progress.",
                placement: "left",
                mobilePlacement: "center",
            },
        ],
    },
    settings: {
        id: "settings",
        title: "Settings",
        description: "Learn the main station, display, CAT, and import/export settings.",
        steps: [
            {
                target: "[data-tour='top-bar-settings']",
                title: "Open Settings",
                content: "Click the settings button to open the settings dialog.",
                waitFor: "[data-tour='settings-modal-content']",
                buttons: action_buttons,
                placement: "bottom",
                skipBeacon: true,
            },
            {
                target: "[data-tour='settings-modal-content']",
                title: "Settings Dialog",
                content:
                    "Settings control your station details, map defaults, display, and imports.",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='settings-general']",
                title: "General Settings",
                content: "The General tab contains station identity and display preferences.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-callsign']",
                title: "Callsign",
                content:
                    "Set your callsign here so submissions and station features know who you are.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-locator']",
                title: "Locator",
                content: "Your locator sets the default map center and distance calculations.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-default-radius']",
                title: "Default Radius",
                content:
                    "This controls the default map radius used around your configured location.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-theme']",
                title: "Theme",
                content: "Choose the visual theme that works best for your operating setup.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-distance-units']",
                title: "Distance Units",
                content: "Switch between kilometers and miles here.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-tab-cat-control']",
                title: "CAT Control",
                content: "Click CAT Control to configure radio integration.",
                optional: true,
                requires: "radio_available",
                buttons: action_buttons,
                placement: "left",
                waitForChange: {
                    selector: "[data-tour='settings-tab-cat-control']",
                    attribute: "data-tour-state",
                    satisfiedValue: "active",
                },
            },
            {
                target: "[data-tour='settings-cat-control']",
                title: "Radio Integration",
                content: "CAT Control settings connect HolyCluster to your radio control software.",
                optional: true,
                requires: "radio_available",
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='settings-tab-bands-modes']",
                title: "Bands And Modes",
                content: "Click Bands & Modes to choose which bands and modes are available.",
                buttons: action_buttons,
                placement: "left",
                waitForChange: {
                    selector: "[data-tour='settings-tab-bands-modes']",
                    attribute: "data-tour-state",
                    satisfiedValue: "active",
                },
            },
            {
                target: "[data-tour='settings-bands-modes']",
                title: "Bands And Modes",
                content: "Disable bands or modes you do not want shown in the main interface.",
                optional: true,
                placement: "left",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='settings-tab-import-export']",
                title: "Import And Export",
                content: "Click Import/Export to manage settings and filter files.",
                buttons: action_buttons,
                placement: "left",
                waitForChange: {
                    selector: "[data-tour='settings-tab-import-export']",
                    attribute: "data-tour-state",
                    satisfiedValue: "active",
                },
            },
            {
                target: "[data-tour='settings-import-export']",
                title: "Import And Export",
                content: "Use this section to back up or restore settings and profile data.",
                optional: true,
                placement: "center",
                mobilePlacement: "center",
            },
            {
                target: "[data-tour='modal-close-button']",
                title: "Close Settings",
                content: "Click Cancel or close the dialog to return to the main interface.",
                optional: true,
                waitForGone: "[data-tour='settings-modal']",
                buttons: action_buttons,
                placement: "auto",
                mobileHideOverlay: true,
            },
        ],
    },
};

export function get_tour_chapter(chapter_id) {
    return TOUR_CHAPTERS[chapter_id] ?? null;
}
