export const TOUR_COMPLETED_CHAPTERS_KEY = "tour_completed_chapters";
export const DEFAULT_TOUR_CHAPTER_ID = "quick_start";

const action_buttons = ["back", "close"];

export const TOUR_CHAPTERS = {
    quick_start: {
        id: "quick_start",
        title: "Quick Start",
        description: "A short introduction to the main Holy Cluster workflow.",
        steps: [
            {
                target: "[data-tour='top-bar']",
                title: "Welcome",
                content:
                    "Welcome to The Holy Cluster. This short tour shows where the main controls live.",
                placement: "bottom",
                skipBeacon: true,
            },
            {
                target: "[data-tour='top-bar-time-limit']",
                title: "Spot Window",
                content: "Use this selector to choose how far back the live spot list should look.",
                placement: "bottom",
            },
            {
                target: "[data-tour='top-bar-submit-spot']",
                title: "Submit Spots",
                content: "This button opens the spot submission form when you want to add a spot.",
                placement: "bottom",
            },
            {
                target: "[data-tour='top-bar-settings']",
                title: "Settings",
                content:
                    "Open settings here to configure your station, display, filters, and imports.",
                placement: "bottom",
            },
            {
                target: "[data-tour='top-bar-left-menu']",
                title: "Open The Filter Rail",
                content: "Click this menu button if the band and mode filter rail is hidden.",
                optional: true,
                waitFor: "[data-tour='left-column']",
                buttons: action_buttons,
                placement: "bottom",
            },
            {
                target: "[data-tour='left-column']",
                title: "Band And Mode Filters",
                content: "The left rail filters spots by band and mode with one-click toggles.",
                optional: true,
                placement: "right",
            },
            {
                target: "[data-tour='mobile-main-tabs']",
                title: "Map And Table Tabs",
                content: "On narrow screens, use these tabs to switch between the map and table.",
                mobileOnly: true,
                optional: true,
                placement: "bottom",
            },
            {
                target: "[data-tour='map-panel']",
                title: "Map",
                content:
                    "The map shows where spots are coming from and gives quick geographic context.",
                desktopOnly: true,
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='table-panel']",
                title: "Spots Table",
                content: "The table gives a detailed sortable view of the current spots.",
                desktopOnly: true,
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='top-bar-right-menu']",
                title: "Open The Side Panel",
                content: "Click this menu button if the side panel is hidden.",
                optional: true,
                waitFor: "[data-tour='side-panel']",
                buttons: action_buttons,
                placement: "bottom",
            },
            {
                target: "[data-tour='side-panel-tabs']",
                title: "Feature Panels",
                content:
                    "These tabs switch between advanced filters, band activity, heatmap, DXpeditions, and missing-worked tools.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='tour-launcher']",
                title: "Tour Launcher",
                content: "Use this launcher to restart this tour or choose a more focused chapter.",
                placement: "top",
            },
        ],
    },
    map: {
        id: "map",
        title: "Map",
        description: "Learn the map controls, overlays, and propagation indicators.",
        steps: [
            {
                target: "[data-tour='mobile-main-tabs']",
                title: "Show The Map",
                content: "Tap the Map tab if the map is not currently visible.",
                mobileOnly: true,
                optional: true,
                waitFor: "[data-tour='map-controls']",
                buttons: action_buttons,
                placement: "bottom",
                skipBeacon: true,
            },
            {
                target: "[data-tour='map-panel']",
                title: "Map View",
                content:
                    "The map shows active spots geographically and helps you spot regional openings.",
                desktopOnly: true,
                optional: true,
                placement: "left",
                skipBeacon: true,
            },
            {
                target: "[data-tour='map-controls']",
                title: "Map Controls",
                content:
                    "These buttons reset the map, open display controls, and switch map features.",
                placement: "left",
            },
            {
                target: "[data-tour='map-reset']",
                title: "Reset Map",
                content: "Use this to return the map to your configured home view.",
                placement: "left",
            },
            {
                target: "[data-tour='map-fullscreen']",
                title: "Fullscreen Map",
                content: "This expands the map for a larger operating view.",
                desktopOnly: true,
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='map-controls-toggle']",
                title: "Open Map Controls",
                content: "Click this controls button to open the map display panel.",
                waitFor: "[data-tour='map-controls-panel']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='map-controls-panel']",
                title: "Display Panel",
                content:
                    "This panel contains map projection, overlays, and geographic display options.",
                placement: "left",
            },
            {
                target: "[data-tour='map-projection-toggle']",
                title: "Projection",
                content: "Switch between the globe and azimuthal projections here.",
                placement: "left",
            },
            {
                target: "[data-tour='map-night-toggle']",
                title: "Night Overlay",
                content: "Toggle the day/night terminator overlay for propagation context.",
                placement: "left",
            },
            {
                target: "[data-tour='map-equator-toggle']",
                title: "Equator",
                content: "This toggles the equator overlay.",
                placement: "left",
            },
            {
                target: "[data-tour='map-overlays']",
                title: "Zone Overlays",
                content:
                    "Use these overlays for DXCC labels, CQ zones, ITU zones, or grid squares.",
                placement: "left",
            },
            {
                target: "[data-tour='map-region-overlays']",
                title: "Regional Overlays",
                content: "These buttons add US state and Canada province overlays when useful.",
                placement: "left",
            },
            {
                target: "[data-tour='propagation-bars']",
                title: "Propagation",
                content: "These indicators summarize current A, K, and solar flux conditions.",
                optional: true,
                requires: "propagation_loaded",
                placement: "top",
            },
        ],
    },
    spots_table: {
        id: "spots_table",
        title: "Spots Table",
        description: "Learn the live spots table, search, sorting, and spot row fields.",
        steps: [
            {
                target: "[data-tour='mobile-main-tabs']",
                title: "Show The Table",
                content: "Tap the Table tab if the spots table is not currently visible.",
                mobileOnly: true,
                optional: true,
                waitFor: "[data-tour='spots-table']",
                buttons: action_buttons,
                placement: "bottom",
                skipBeacon: true,
            },
            {
                target: "[data-tour='table-panel']",
                title: "Table View",
                content: "The table is the detailed sortable view of live spots.",
                desktopOnly: true,
                optional: true,
                placement: "left",
                skipBeacon: true,
            },
            {
                target: "[data-tour='spots-table']",
                title: "Spots Table",
                content:
                    "New spots appear here with callsign, frequency, band, mode, and comment data.",
                placement: "left",
            },
            {
                target: "[data-tour='table-search']",
                title: "Callsign Search",
                content:
                    "Search for a callsign here, then press Enter to create a show-only filter.",
                desktopOnly: true,
                optional: true,
                placement: "bottom",
            },
            {
                target: "[data-tour='table-search-mobile']",
                title: "Callsign Search",
                content:
                    "Search for a callsign here, then press Enter to create a show-only filter.",
                mobileOnly: true,
                optional: true,
                placement: "top",
            },
            {
                target: "[data-tour='table-search-single-spot-toggle']",
                title: "Single Spot Mode",
                content: "This toggles whether only the newest spot per station is shown.",
                desktopOnly: true,
                optional: true,
                placement: "bottom",
            },
            {
                target: "[data-tour='table-search-mobile-single-spot-toggle']",
                title: "Single Spot Mode",
                content: "This toggles whether only the newest spot per station is shown.",
                mobileOnly: true,
                optional: true,
                placement: "top",
            },
            {
                target: "[data-tour='table-header-row']",
                title: "Columns And Sorting",
                content: "Click sortable headers to change the table order.",
                placement: "bottom",
            },
            {
                target: "[data-tour='spot-row']",
                title: "Spot Row",
                content: "Each row is one received spot. Click a row to pin it on the map.",
                optional: true,
                requires: "has_spots",
                placement: "top",
            },
            {
                target: "[data-tour='spot-row-flag']",
                title: "Entity",
                content: "This cell shows the spotted station's country or entity.",
                optional: true,
                requires: "has_spots",
                placement: "top",
            },
            {
                target: "[data-tour='spot-row-dx-callsign']",
                title: "DX Callsign",
                content: "The DX callsign links to its QRZ page and can be highlighted by alerts.",
                optional: true,
                requires: "has_spots",
                placement: "top",
            },
            {
                target: "[data-tour='spot-row-frequency']",
                title: "Frequency",
                content: "Click the frequency to send mode and frequency to the connected radio.",
                optional: true,
                requires: "has_spots",
                placement: "top",
            },
            {
                target: "[data-tour='spot-row-band']",
                title: "Band",
                content: "The band column helps you scan activity by band at a glance.",
                optional: true,
                requires: "has_spots",
                placement: "top",
            },
            {
                target: "[data-tour='spot-row-mode']",
                title: "Mode",
                content: "The mode column shows how the spot was classified.",
                optional: true,
                requires: "has_spots",
                placement: "top",
            },
            {
                target: "[data-tour='spot-row-comment']",
                title: "Comment",
                content: "On wide screens, comments provide extra spot details and references.",
                desktopOnly: true,
                optional: true,
                requires: "has_spots",
                placement: "top",
            },
        ],
    },
    filters: {
        id: "filters",
        title: "Filters",
        description: "Learn the band, mode, and advanced filter controls.",
        steps: [
            {
                target: "[data-tour='top-bar-left-menu']",
                title: "Open The Filter Rail",
                content: "Click this menu button if the band and mode filter rail is hidden.",
                optional: true,
                waitFor: "[data-tour='left-column']",
                buttons: action_buttons,
                placement: "bottom",
                skipBeacon: true,
            },
            {
                target: "[data-tour='left-column']",
                title: "Quick Filters",
                content:
                    "The left rail contains fast band and mode filters for the live spot stream.",
                optional: true,
                placement: "right",
                skipBeacon: true,
            },
            {
                target: "[data-tour='band-filter-group']",
                title: "Band Filters",
                content: "Toggle bands on or off here. Counts show how many current spots match.",
                optional: true,
                placement: "right",
            },
            {
                target: "[data-tour='mode-filter-group']",
                title: "Mode Filters",
                content: "Use these buttons to limit the table and map to selected modes.",
                optional: true,
                placement: "right",
            },
            {
                target: "[data-tour='radio-band-filter-group']",
                title: "Radio Band Filter",
                content: "When a radio is available, this can follow the current radio band.",
                optional: true,
                requires: "radio_available",
                placement: "right",
            },
            {
                target: "[data-tour='top-bar-right-menu']",
                title: "Open The Side Panel",
                content: "Click this menu button if the advanced filter panel is hidden.",
                optional: true,
                waitFor: "[data-tour='side-panel']",
                buttons: action_buttons,
                placement: "bottom",
            },
            {
                target: "[data-tour='side-panel-tab-filters']",
                title: "Filters Tab",
                content:
                    "Click the Filters tab to show advanced alert, show-only, and hide filters.",
                optional: true,
                waitFor: "[data-tour='filters-panel']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='filters-panel']",
                title: "Advanced Filters",
                content:
                    "Advanced filters can alert, show only matching spots, or hide matching spots.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='filter-section-alert']",
                title: "Alert Filters",
                content: "Alert filters keep matching spots visible and visually highlighted.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='filter-section-show_only']",
                title: "Show-Only Filters",
                content: "Show-only filters limit the interface to matching spots.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='filter-section-hide']",
                title: "Hide Filters",
                content: "Hide filters remove matching spots from the table and map.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='add-filter-button-alert']",
                title: "Create A Filter",
                content: "Click Add to open the filter editor for a new alert filter.",
                optional: true,
                waitFor: "[data-tour='filter-modal']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='filter-modal']",
                title: "Filter Editor",
                content:
                    "The editor lets you define callsign, entity, zone, comment, and missing-worked filters.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='modal-cancel-button']",
                title: "Close The Editor",
                content: "Click Cancel or close the dialog to return to the filter panel.",
                optional: true,
                waitForGone: "[data-tour='filter-modal']",
                buttons: action_buttons,
                placement: "top",
            },
        ],
    },
    side_panel: {
        id: "side_panel",
        title: "Side Panel",
        description: "Tour the non-dev side panel tools and tabs.",
        steps: [
            {
                target: "[data-tour='top-bar-right-menu']",
                title: "Open The Side Panel",
                content: "Click this menu button if the side panel is hidden.",
                optional: true,
                waitFor: "[data-tour='side-panel']",
                buttons: action_buttons,
                placement: "bottom",
                skipBeacon: true,
            },
            {
                target: "[data-tour='side-panel']",
                title: "Side Panel",
                content:
                    "The side panel groups deeper tools that do not fit in the main map/table view.",
                optional: true,
                placement: "left",
                skipBeacon: true,
            },
            {
                target: "[data-tour='side-panel-tabs']",
                title: "Panel Tabs",
                content: "Use these tabs to switch between the side panel tools.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='side-panel-tab-filters']",
                title: "Filters View",
                content: "Click the Filters tab to show the advanced filter builder.",
                optional: true,
                waitFor: "[data-tour='side-panel-view-filters']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='side-panel-view-filters']",
                title: "Filters View",
                content: "This view contains advanced alert, show-only, and hide filter sections.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='side-panel-tab-band-bar']",
                title: "Band Bar View",
                content: "Click the Band Bar tab to inspect activity by band.",
                optional: true,
                waitFor: "[data-tour='band-bar-panel']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='band-bar-panel']",
                title: "Band Activity",
                content:
                    "The band bar summarizes activity and spot distribution for a selected band.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='band-bar-selector']",
                title: "Band Selector",
                content: "Choose which band the activity chart should show.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='band-bar-chart']",
                title: "Activity Chart",
                content: "The chart helps you quickly compare activity within the selected band.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='band-bar-legend']",
                title: "Legend",
                content: "The legend explains the chart colors and categories.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='side-panel-tab-heatmap']",
                title: "Heatmap View",
                content: "Click the Heatmap tab to inspect activity density by region.",
                optional: true,
                waitFor: "[data-tour='heatmap-panel']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='heatmap-panel']",
                title: "Heatmap",
                content: "The heatmap highlights where current activity is concentrated.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='heatmap-continent-selector']",
                title: "Heatmap Region",
                content: "Change the selected continent to focus the heatmap.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='side-panel-tab-dxpeditions']",
                title: "DXpeditions View",
                content: "Click the DXpeditions tab to show tracked expedition activity.",
                optional: true,
                waitFor: "[data-tour='dxpeditions-panel']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='dxpeditions-panel']",
                title: "DXpeditions",
                content: "This panel tracks active DXpeditions and their related spots.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='dxpeditions-summary']",
                title: "DXpedition Summary",
                content: "The summary shows the current expedition activity at a glance.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='dxpeditions-filter']",
                title: "DXpedition Filters",
                content: "Use these controls to narrow which DXpeditions are shown.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='dxpeditions-sort']",
                title: "DXpedition Sorting",
                content: "Sort DXpeditions by the view that is most useful while operating.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='side-panel-tab-missing']",
                title: "Missing View",
                content: "Click the Missing tab to show worked/missing tracking.",
                optional: true,
                waitFor: "[data-tour='hunter-panel']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='hunter-panel']",
                title: "Missing And Worked",
                content:
                    "This panel uses your ADIF data to track what you have worked and still need.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='hunter-adif-import']",
                title: "ADIF Import",
                content:
                    "Import ADIF logs here so the missing-worked tools can track your progress.",
                optional: true,
                placement: "left",
            },
        ],
    },
    settings: {
        id: "settings",
        title: "Settings",
        description: "Learn the main station, display, CAT, and import/export settings.",
        steps: [
            {
                target: "[data-tour='top-bar-settings']",
                title: "Open Settings",
                content: "Click the settings button to open the settings dialog.",
                waitFor: "[data-tour='settings-modal']",
                buttons: action_buttons,
                placement: "bottom",
                skipBeacon: true,
            },
            {
                target: "[data-tour='settings-modal']",
                title: "Settings Dialog",
                content:
                    "Settings control your station details, map defaults, display, and imports.",
                placement: "left",
            },
            {
                target: "[data-tour='settings-tabs']",
                title: "Settings Sections",
                content: "Use these tabs to move between groups of settings.",
                placement: "left",
            },
            {
                target: "[data-tour='settings-general']",
                title: "General Settings",
                content: "The General tab contains station identity and display preferences.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-callsign']",
                title: "Callsign",
                content:
                    "Set your callsign here so submissions and station features know who you are.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-locator']",
                title: "Locator",
                content: "Your locator sets the default map center and distance calculations.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-default-radius']",
                title: "Default Radius",
                content:
                    "This controls the default map radius used around your configured location.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-theme']",
                title: "Theme",
                content: "Choose the visual theme that works best for your operating setup.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-distance-units']",
                title: "Distance Units",
                content: "Switch between kilometers and miles here.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-tab-cat-control']",
                title: "CAT Control",
                content: "Click CAT Control to configure radio integration.",
                optional: true,
                requires: "radio_available",
                waitFor: "[data-tour='settings-cat-control']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='settings-cat-control']",
                title: "Radio Integration",
                content: "CAT Control settings connect HolyCluster to your radio control software.",
                optional: true,
                requires: "radio_available",
                placement: "left",
            },
            {
                target: "[data-tour='settings-tab-bands-modes']",
                title: "Bands And Modes",
                content: "Click Bands & Modes to choose which bands and modes are available.",
                waitFor: "[data-tour='settings-bands-modes']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='settings-bands-modes']",
                title: "Bands And Modes",
                content: "Disable bands or modes you do not want shown in the main interface.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='settings-tab-import-export']",
                title: "Import And Export",
                content: "Click Import/Export to manage settings and filter files.",
                waitFor: "[data-tour='settings-import-export']",
                buttons: action_buttons,
                placement: "left",
            },
            {
                target: "[data-tour='settings-import-export']",
                title: "Import And Export",
                content: "Use this section to back up or restore settings and profile data.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='modal-cancel-button']",
                title: "Close Settings",
                content: "Click Cancel or close the dialog to return to the main interface.",
                optional: true,
                waitForGone: "[data-tour='settings-modal']",
                buttons: action_buttons,
                placement: "top",
            },
        ],
    },
    submit_spot: {
        id: "submit_spot",
        title: "Submit Spot",
        description: "Learn how to submit a new spot from the top bar.",
        steps: [
            {
                target: "[data-tour='top-bar-submit-spot']",
                title: "Open Submit Spot",
                content: "Click this button to open the spot submission form.",
                waitFor: "[data-tour='submit-spot-modal']",
                buttons: action_buttons,
                placement: "bottom",
                skipBeacon: true,
            },
            {
                target: "[data-tour='submit-spot-modal']",
                title: "Submit Spot Dialog",
                content: "Use this form to send a new DX spot to the cluster.",
                placement: "left",
            },
            {
                target: "[data-tour='submit-spot-form']",
                title: "Spot Form",
                content:
                    "The form captures who spotted the station, the DX callsign, frequency, and comment.",
                placement: "left",
            },
            {
                target: "[data-tour='submit-spot-spotter-callsign']",
                title: "Spotter Callsign",
                content: "This uses the station callsign configured in settings.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='submit-spot-dx-callsign']",
                title: "DX Callsign",
                content: "Enter the callsign being spotted here.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='submit-spot-frequency']",
                title: "Frequency",
                content: "Enter the spotted frequency in kHz.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='submit-spot-comment']",
                title: "Comment",
                content: "Use the comment field for short operating details or notes.",
                optional: true,
                placement: "left",
            },
            {
                target: "[data-tour='modal-cancel-button']",
                title: "Close Submit Spot",
                content: "Click Cancel or close the dialog to return to the main interface.",
                optional: true,
                waitForGone: "[data-tour='submit-spot-modal']",
                buttons: action_buttons,
                placement: "top",
            },
        ],
    },
};

export function get_tour_chapter(chapter_id) {
    return TOUR_CHAPTERS[chapter_id] ?? null;
}
