"""baseline

Revision ID: 68a8d1bc052f
Revises:
Create Date: 2026-03-26 00:33:57.974816

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "68a8d1bc052f"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("holy_spots2", "spotter_state", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("holy_spots2", "dx_state", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("spots_with_issues2", "spotter_state", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("spots_with_issues2", "dx_state", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("spots_with_issues2", "dx_state", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("spots_with_issues2", "spotter_state", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("holy_spots2", "dx_state", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("holy_spots2", "spotter_state", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
