"""add inecies to HolySpot and Progagation

Revision ID: f489c957a156
Revises: a9b8c7d6e5f4
Create Date: 2026-06-28 22:32:51.384748

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f489c957a156'
down_revision: Union[str, Sequence[str], None] = 'a9b8c7d6e5f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_holy_spots2_timestamp'), 'holy_spots2', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holy_spots2_timestamp'), table_name='holy_spots2')
    # ### end Alembic commands ###
