name: Build and upload catserve

on:
  push:
    paths:
      - "catserver/**"
      - ".github/workflows/catserver.yml"
    branches:
      - "master"
    tags:
      - "catserver-v*"

env:
  TARGET: x86_64-pc-windows-gnu

jobs:
  build-catserver:
    name: Build Catserver
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/iarc-il/catserver-ci:latest
      options: --user root
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Setup SSH
        run: |
          export HOME=/root
          mkdir -p $HOME/.ssh
          chmod 700 $HOME/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          ssh-keyscan -H "${{ secrets.DEPLOY_HOST_DEV }}" >> $HOME/.ssh/known_hosts
          ssh-keyscan -H "${{ secrets.DEPLOY_HOST_PROD }}" >> $HOME/.ssh/known_hosts
          chmod 644 $HOME/.ssh/known_hosts

      - name: Cache Rust dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            catserver/target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - name: Fix git errors
        run: |
          git config --system --add safe.directory "$GITHUB_WORKSPACE"
          git fetch --tags --force

      - name: Run rustfmt
        working-directory: catserver
        run: cargo fmt --check

      - name: Run Clippy
        working-directory: ./catserver
        run: cargo clippy --target $TARGET -- -D warnings

      - name: Build catserver
        working-directory: ./catserver
        run: cargo build --target $TARGET --release

      - name: Change build artifacts ownership
        working-directory: ./catserver
        run: chown -R wix:wix target

      - name: Build installer
        working-directory: ./catserver
        run: su wix -c "./build_msi.sh in-docker"

      - name: Upload to Development Server
        if: github.ref == 'refs/heads/master'
        run: |
          bash catserver/publish.sh \
            --deploy-user ${{ secrets.DEPLOY_USER_DEV }} \
            --deploy-host ${{ secrets.DEPLOY_HOST_DEV }} \
            --local-msi-path catserver/target/$TARGET/release/HolyCluster.msi \
            --remote-msi-dir /opt/msi

      - name: Upload to Production Server
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          bash catserver/publish.sh \
            --deploy-user ${{ secrets.DEPLOY_USER_PROD }} \
            --deploy-host ${{ secrets.DEPLOY_HOST_PROD }} \
            --local-msi-path catserver/target/$TARGET/release/HolyCluster.msi \
            --remote-msi-dir /opt/msi
